mode: "deployment"
image:
  repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
config:
  exporters:
    otlp/jaeger:
      endpoint: spring-oracledb-observability-jaeger-collector:4317
      tls:
        insecure: true
    debug:
      verbosity: basic
  extensions:
    health_check: {}
  processors:
    memory_limiter: null
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317
  service:
    extensions:
      - health_check
    pipelines:
      logs: null
      metrics: null
      traces:
        receivers: [otlp]
        processors: []
        exporters: [otlp/jaeger]